loki:
  auth_enabled: false

gateway:
  enabled: true
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internal

singleBinary:
  replicas: 1
